Main: main.class 
	java Main
main.class: Main.java Rectangle.class Square.class
	javac Main.java
Rectangle.class: Rectangle.java Shape.class
	javac Rectangle.java
Square.class: Square.java Shape.class
	javac Square.java
Shape.class: Shape.java
	javac Shape.java
